spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234

token:
  expiration_time: 8640000000
  secret: user_token_default_changed1111

gateway:
  ip: 10.10.5.73
